version: ""
services:  
   shop:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      DATABASE_URI: $DATABASE_URI
      ADMINS: $ADMINS
      LOG_CHANNEL: $LOG_CHANNEL
